# Generated by Django 3.0.8 on 2020-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
