# Generated by Django 3.0.8 on 2020-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0002_blogs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_updated',
            field=models.DateTimeField(default=None),
        ),
    ]
