# Generated by Django 3.0.8 on 2020-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0003_auto_20200719_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
